Object AmericaCommandCenter
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End


Object AmericaVehicleDozer
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End

Object AmericaPowerPlant
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End


Object AmericaParticleCannonUplink
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End



Object AmericaStrategyCenter
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End


Object AmericaAirfield
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End


Object AmericaSupplyCenter
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End


Object AmericaSupplyDropZone
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End


Object AmericaBarracks
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End


Object AmericaWarFactory
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End



Object AmericaPatriotBattery
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End

Object AmericaFireBase
  AddModule 
  Behavior = StealthUpdate ModuleTag_NolanStealth
    StealthDelay                = 2000 ; msec
    StealthForbiddenConditions  = ATTACKING USING_ABILITY TAKING_DAMAGE
    HintDetectableConditions    = IS_FIRING_WEAPON 
    FriendlyOpacityMin          = 50.0%
    FriendlyOpacityMax          = 100.0%
    InnateStealth               = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes

  End
  End
End



Object ChinaPropagandaCenter
 AddModule
  Behavior = ProductionUpdate ModuleTag_10AA
    ; nothing
  End
  Behavior = DefaultProductionExitUpdate ModuleTag_11AA
    UnitCreatePoint   = X:  0.0  Y:  45.0   Z:0.0
    NaturalRallyPoint = X: 42.0  Y:  45.0   Z:0.0;NaturalRallyPointX must always match GeometryMajorRadius! -ML
  End
 End
End
