WaterTransparency
  TransparentWaterMinOpacity = 0.8   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 2.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
  StandingWaterTexture = TSWater03.tga
  ;StandingWaterColor = R:0 G:50 B:0
  ;StandingWaterColor = R:100 G:150 B:100
  StandingWaterColor = R:50 G:75 B:50
  ;AdditiveBlending = Yes
  RadarWaterColor = R:100 G:196 B:100
End

DialogEvent Taunts_GLABoss001
Filename = mg1arm01.wav
End

DialogEvent Taunts_GLABoss002
Filename = mg1ofg01.wav
End

DialogEvent Taunts_GLABoss003
Filename = mg1sc105.wav
End

DialogEvent Taunts_GLABoss004
Filename = mc1ba103.wav
End

DialogEvent Taunts_GLABoss005
Filename = mc1ba201.wav
End

DialogEvent Taunts_GLABoss006
Filename = mc1mi101.wav
End

DialogEvent Taunts_GLABoss007
Filename = mc1mi102.wav
End

DialogEvent Taunts_GLABoss008
Filename = mc1mi103.wav
End

DialogEvent Taunts_GLABoss009
Filename = mc1mi104.wav
End

DialogEvent Taunts_GLABoss010
Filename = mc1ofc04.wav
End

DialogEvent Taunts_GLABoss011
Filename = mc1te101.wav
End

DialogEvent Taunts_GLABoss012
Filename = mc1ofg01.wav
End

DialogEvent Taunts_GLABoss013
Filename = mc1te201.wav
End

DialogEvent Taunts_GLABoss014
Filename = mc1ba201.wav
End

DialogEvent Taunts_GLABoss015
Filename = mg1ofg06.wav
End

DialogEvent Taunts_GLABoss016
Filename = mg1ofg01.wav
End

DialogEvent Taunts_GLABoss017
Filename = mg1sc106.wav
End

DialogEvent Taunts_GLABoss018
Filename = mg1sc103.wav
End

DialogEvent Taunts_GLABoss019
Filename = mg1sc111.wav
End

DialogEvent Taunts_GLABoss020
Filename = mg1sc202.wav
End

DialogEvent Taunts_GLABoss021
Filename = mg1sc206.wav
End

DialogEvent Taunts_GLABoss022
Filename = mg1sc110.wav
End


