Object AmericaParticleCannonUplink
  ShroudRevealToAllRange = 0  ; Reveals shroud to all players at a specific amount which can be different. 
                               ; Using same value? Then use KINDOF_REVEAL_TO_ALL instead!
END

Object GLAScudStorm
  ShroudRevealToAllRange = 0  ; Reveals shroud to all players at a specific amount which can be different. 
                               ; Using same value? Then use KINDOF_REVEAL_TO_ALL instead!
END

DialogEvent Taunts_GLABoss001
Filename = mu6com01.wav
End

DialogEvent Taunts_GLABoss002
Filename = mu6com08.wav
End

DialogEvent Taunts_GLABoss003
Filename = mg5cr201.wav
End

DialogEvent Taunts_GLABoss004
Filename = mu2cr202.wav
End

DialogEvent Taunts_GLABoss005
Filename = mg5rp102.wav
End

DialogEvent Taunts_GLABoss006
Filename = mg5rp103.wav
End

DialogEvent Taunts_GLABoss007
Filename = mg5rp104.wav
End

DialogEvent Taunts_GLABoss008
Filename = mu1cr104.wav
End

DialogEvent Taunts_GLABoss009
Filename = mu1cr105.wav
End

DialogEvent Taunts_GLABoss010
Filename = mu1cr107.wav
End

DialogEvent Taunts_GLABoss011
Filename = mg5bu104.wav
End

DialogEvent Taunts_GLABoss012
Filename = mg5bu103.wav
End

DialogEvent Taunts_GLABoss013
Filename = mg5bu106.wav
End

DialogEvent Taunts_GLABoss014
Filename = mg5bu108.wav
End

DialogEvent Taunts_GLABoss015
Filename = mg5ofg04.wav
End

DialogEvent Taunts_GLABoss016
Filename = mg5ofg05.wav
End

DialogEvent Taunts_GLABoss017
Filename = mg5ofg11.wav
End

DialogEvent Taunts_GLABoss018
Filename = mg5qu104.wav
End

DialogEvent Taunts_GLABoss019
Filename = mg5qu201.wav
End

DialogEvent Taunts_GLABoss020
Filename = mg5qu202.wav
End

DialogEvent Taunts_GLABoss021
Filename = mg5xog02.wav
End

DialogEvent Taunts_GLABoss022
Filename = mg5xog04.wav
End

DialogEvent Taunts_GLABoss023
Filename = mg5xog05.wav
End

DialogEvent Taunts_GLABoss024
Filename = mg5xog06.wav
End

DialogEvent Taunts_GLABoss025
Filename = mg5xog07.wav
End

DialogEvent Taunts_GLABoss026
Filename = mg5xog08.wav
End

DialogEvent Taunts_GLABoss027
Filename = mg5xog10.wav
End

DialogEvent Taunts_GLABoss028
Filename = mg6ofg03.wav
End

DialogEvent Taunts_GLABoss029
Filename = mg6rb103.wav
End

DialogEvent Taunts_GLABoss030
Filename = mg6rb107.wav
End

DialogEvent Taunts_GLABoss031
Filename = mg7xog12.wav
End

DialogEvent Taunts_GLABoss032
Filename = mg7xog14.wav
End
