Object AmericaParticleCannonUplink
  ShroudRevealToAllRange = 0  ; Reveals shroud to all players at a specific amount which can be different. 
                               ; Using same value? Then use KINDOF_REVEAL_TO_ALL instead!
END

Object GLAScudStorm
  ShroudRevealToAllRange = 0  ; Reveals shroud to all players at a specific amount which can be different. 
                               ; Using same value? Then use KINDOF_REVEAL_TO_ALL instead!
END