
; Prisons are cut. sorry. (srj)
;Object GLAPrison
;Buildable = No
;END

;AIData
  ;StructureSeconds = 6.6 ;  Ai tries to build a new structure every N seconds.
  ;TeamSeconds = 50 ;  Ai tries to build a new team every N seconds.
  ;Wealthy = 14000 ;   Number of resources for the AI to consider itself wealthy
  ;Poor = 2000 ;   Number of resources for the AI to consider itself poor
  ;StructuresWealthyRate = 2.0 ;  (2=twice as fast) Rate modifier for structure building when wealthy.
  ;StructuresPoorRate = 0.6 ;  (0.5=half as fast) Rate modifier for structures when poor.
  ;TeamsWealthyRate = 1.5 ;   (2=twice as fast) Rate modifier for teams building when wealthy.
  ;TeamsPoorRate = 1.0 ;  (0.5=half as fast) Rate modifier for teams when poor.
  ;TeamResourcesToStart = 0.80 ; (1.0=100%) Amount of resources required to start building a team. 
  ;GuardInnerModifierAI = 1.0 ;The radius modifier to vision which a guarding (AI Controlled) unit will agressively attack
  ;GuardOuterModifierAI = 2.0 ;The radius modifier to vision which a guarding (AI Controlled) unit will chase after
;  GuardInnerModifierHuman = 0.67 ;The radius modifier to vision which a guarding (Human Controlled) unit will agressively attack
;  GuardOuterModifierHuman = 1.0  ;The radius modifier to vision which a guarding (Human Controlled) unit will chase after
 ; GuardChaseUnitsDuration = 10000 ;The number of msec for which a guarding unit will chase attackers before giving up
  ;AttackPriorityDistanceModifier = 100.0; The distance required to reduce attack priority by 1.
  ;MaxRecruitRadius = 1500.0; The maximum distance a unit will be from a unit that recruits it.
;End

;hostile build

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End

SpecialPower SuperweaponDaisyCutter
  Enum                = SPECIAL_DAISY_CUTTER
  ReloadTime          = 480000   ; in milliseconds
  RequiredScience     = SCIENCE_DaisyCutter
  PublicTimer         = Yes
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 30000  ; Lifetime of a Look done belonging to the firing player
  ViewObjectRange     = 250 ; And how far it can see
  RadiusCursorRadius  = 100
End

SpecialPower SuperweaponCarpetBomb
  Enum                = SPECIAL_CARPET_BOMB
  ReloadTime          = 600000   ; in milliseconds
  RequiredScience     = SCIENCE_CarpetBomb
  PublicTimer         = Yes
  ViewObjectDuration  = 30000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 100
End

;; -------------------------------------
;; GLA Sciences
;; -------------------------------------


Object Object ChineeseSpyPost
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END




;-----------------------------------------------------------------------
Object Slth_GLAVehicleQuadCannon
AddModule ModuleTag_69
Behavior = StealthUpdate ModuleTag_69
    StealthDelay                          = 2000 ; msec
    StealthForbiddenConditions            = ATTACKING
    InnateStealth                         = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes
  End
End
End