Object PoliceCar
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
      CrateData            = GLA02_Always100DollarCrate
    End
  End
END

Object CarEuroPoliceVan
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
      CrateData            = GLA02_Always100DollarCrate
    End
  End
END

Object Chinabarracks
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object Chinabunker
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object ChinaCommandCenter
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object ChinaPowerPlant
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object ChinaPropagandaCenter
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object ChinaSpeakerTower
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object SupplyCenter
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object ChinaWarFactory
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object ConvienceStore
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object IndustrialBuilding02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object SovietRadioBuilding
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object StanSovietOffice02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object StanSovietOffice01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object MogadishuHighrise01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object MogadishuHighrise02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object MogadishuHighrise03
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object CivilianHighrise02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object CivilianHighrise01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object AsianBank
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object EuropeanParkingGarage
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AsianArcade
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AsianRetailStore01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AsianRetailStore02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AsianDealership
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AsianNightClub
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AsianApartmentUnit
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END

Object AsianOffice01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object SovietGovernmentBuildingSmall
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END


Object EuroHighrise
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END


Object SovietBuilding
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END


Object AsiaGovernmentBuilding
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END


Object Civilianhighrise01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END


Object AsiaApartment02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END


Object AsianHotel01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object CivilianAirport
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

; Prisons are cut. sorry. (srj)
;Object GLAPrison
;Buildable = No
;END


Object 100DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 100
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      HumanOnly      = Yes
    End
  End
END

Object 200DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 200
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      HumanOnly      = No
    End
  End
END

Object 1000DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 1000
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      HumanOnly      = Yes
    End
  End
END

Object 1500DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 1500
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      HumanOnly      = Yes
    End
  End
END

Object 2500DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 2500
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      HumanOnly      = Yes
    End
  End
END

Locomotor LimoLocomotor
  Surfaces = GROUND
  Speed = 50                ; in dist/sec
  SpeedDamaged = 50         ; in dist/sec
  TurnRate = 120            ; in degrees/sec
  TurnRateDamaged = 120     ; in degrees/sec
  Acceleration = 30         ; in dist/(sec^2)
  AccelerationDamaged = 30  ; in dist/(sec^2)
  Braking = 50              ; in dist/(sec^2)
  MinTurnSpeed = 40         ; in dist/sec
  TurnPivotOffset = -0.5    ; where to pivot when turning (-1.0 = rear, 0.0 = center, 1.0 = front)
  ZAxisBehavior = NO_Z_MOTIVE_FORCE
  Appearance = FOUR_WHEELS

  AccelerationPitchLimit = 6      ; Angle limit how far chassis will lift or roll from acceleration.
  BounceAmount = 0                ;  simulates hitting random rocks.  0==smooth pavement, 200 = bumpy.
  PitchStiffness = 0.1            ;  stiffness of the "springs" in the suspension forward & back.
  RollStiffness  = 0.05            ;  stiffness of the "springs" in the suspension side to side.
  PitchDamping = 0.5        ;  How fast it damps.  0=perfect spring, bounces forever.  1=glued to terrain.
  RollDamping = 0.5        ;  How fast it damps.  0=perfect spring, bounces forever.  1=glued to terrain.
  ForwardAccelerationPitchFactor = 0.3  ; How much acceleration will cause the front to lift, or dip for stops.
  LateralAccelerationRollFactor = 0.2   ;   How much cornering will cause the chassis to roll.
End

Object CarLimo3
  Locomotor = SET_NORMAL LimoLocomotor
End

Locomotor BasicCarLocomotor
  Surfaces = GROUND
  Speed = 50                ; in dist/sec
  SpeedDamaged = 50         ; in dist/sec
  TurnRate = 120            ; in degrees/sec
  TurnRateDamaged = 120     ; in degrees/sec
  Acceleration = 20         ; in dist/(sec^2)
  AccelerationDamaged = 20  ; in dist/(sec^2)
  Braking = 50              ; in dist/(sec^2)
  MinTurnSpeed = 30         ; in dist/sec
  TurnPivotOffset = -0.5    ; where to pivot when turning (-1.0 = rear, 0.0 = center, 1.0 = front)
  ZAxisBehavior = NO_Z_MOTIVE_FORCE
  Appearance = FOUR_WHEELS

  AccelerationPitchLimit = 6      ; Angle limit how far chassis will lift or roll from acceleration.
  BounceAmount = 0                ;  simulates hitting random rocks.  0==smooth pavement, 200 = bumpy.
  PitchStiffness = 0.1            ;  stiffness of the "springs" in the suspension forward & back.
  RollStiffness  = 0.05            ;  stiffness of the "springs" in the suspension side to side.
  PitchDamping = 0.5        ;  How fast it damps.  0=perfect spring, bounces forever.  1=glued to terrain.
  RollDamping = 0.5        ;  How fast it damps.  0=perfect spring, bounces forever.  1=glued to terrain.
  ForwardAccelerationPitchFactor = 0.3  ; How much acceleration will cause the front to lift, or dip for stops.
  LateralAccelerationRollFactor = 0.2   ;   How much cornering will cause the chassis to roll.
End

Weapon ComancheAntiTankMissileWeapon
  ; only restate the fields that are *changed*, please
  ClipSize = 0              ; how many shots in a Clip (0 == infinite)
End

Weapon ComancheRocketPodWeapon
  ; only restate the fields that are *changed*, please
  ClipSize = 0              ; how many shots in a Clip (0 == infinite)
End



Locomotor CINE_BasicCarLocomotor
  Speed = 140
  SpeedDamaged = 140
  Acceleration = 60
  AccelerationDamaged = 60
End





WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End




;; -------------------------------------
;; GLA Sciences
;; -------------------------------------

Object Chem_GLABlackMarket
MaxSimultaneousOfType = 1
End




Object PoliceCar
  ; ***DESIGN parameters ***
  CrusherLevel           = 0  ;What can I crush?: 1 = infantry, 2 = trees, 3 = vehicles
End

Object CarEuroPoliceVan
  ; ***DESIGN parameters ***
  CrusherLevel           = 0  ;What can I crush?: 1 = infantry, 2 = trees, 3 = vehicles
End
