;GLA07 Map.ini


;Object GLAVehicleBombTruck
;Buildable = No
;END

;Object GLAScudStorm
;Buildable = No
;END

;Object GLAPrison
;Buildable = No
;END


Object ConvoyTruckArmedWithNuke
RadarPriority = UNIT

 ReplaceModule ModuleTag_02
   Body              = ActiveBody ModuleTag_02_Override
     MaxHealth       = 1000.0
     InitialHealth   = 1000.0
   End
 End
END

Object MogadishuGarage
SoundAmbient = Amb_DesertVillageMilitary
END

;AIData
 ;StructureSeconds = 10.0 ;  Ai tries to build a new structure every N seconds.
 ; TeamSeconds = 50.0 ;  Ai tries to build a new team every N seconds.
 ; Wealthy = 14000 ;   Number of resources for the AI to consider itself wealthy
  ;Poor = 2000 ;   Number of resources for the AI to consider itself poor
  ;StructuresWealthyRate = 1.5 ;  (2=twice as fast) Rate modifier for structure building when wealthy.
  ;StructuresPoorRate = 0.6 ;  (0.5=half as fast) Rate modifier for structures when poor.
  ;TeamsWealthyRate = 1.5 ;   (2=twice as fast) Rate modifier for teams building when wealthy.
  ;TeamsPoorRate = 1.0 ;  (0.5=half as fast) Rate modifier for teams when poor.
  ;TeamResourcesToStart = 0.80 ; (1.0=100%) Amount of resources required to start building a team. 
 ; GuardInnerModifierAI = 0.67 ;The radius modifier to vision which a guarding (AI Controlled) unit will agressively attack
  ;GuardOuterModifierAI = 1.0 ;The radius modifier to vision which a guarding (AI Controlled) unit will chase after
;  GuardInnerModifierHuman = 0.67;The radius modifier to vision which a guarding (Human Controlled) unit will agressively attack
;  GuardOuterModifierHuman = 1.0  ;The radius modifier to vision which a guarding (Human Controlled) unit will chase after
  ;GuardChaseUnitsDuration = 5000 ;The number of msec for which a guarding unit will chase attackers before giving up
 ; AlertRangeModifier = 1.1 ;The adjustment applied when a unit is alert and doing various scans for enemies (AI units only)
 ; AggressiveRangeModifier = 1.5 ;The adjustment applied when a unit is aggressive and doing various scans for enemies (AI units only)
  ;AttackPriorityDistanceModifier = 100.0; The distance required to reduce attack priority by 1.
  ;MaxRecruitRadius = 1500.0; The maximum distance a unit will be from a unit that recruits it.
  ;ForceIdleMSEC = 67 ;The number of milisec a unit must be idle before looking for an enemy, 2 frames.
 ; EnableRepulsors = Yes ; If yes, KINDOF_CAN_BE_REPULSED will run from enemies & repulsors.
  ;RepulsedDistance = 150.0 ; How far beyond vision range a repulsed civilian will run before stopping.
 ; MinVehiclesForGroup       = 5        ; Have to have 5 vehicles to do group movement.  

  ;SideInfo GLA
   ; ResourceGatherersEasy     = 6
   ; ResourceGatherersNormal   = 6
    ;ResourceGatherersHard     = 6     
    ;BaseDefenseStructure1     = GLATunnelNetwork  

    ;SkillSet1
     ; Science = SCIENCE_TechnicalTraining
     ; Science = SCIENCE_MarauderTank
     ; Science = SCIENCE_RebelAmbush3
     ; Science = SCIENCE_CashBounty3
     ; Science = SCIENCE_RebelAmbush2
     ; Science = SCIENCE_CashBounty2
     ; Science = SCIENCE_AnthraxBomb
   ; End

    ;SkillSet2
      ;Science = SCIENCE_TechnicalTraining
     ; Science = SCIENCE_MarauderTank
     ; Science = SCIENCE_RebelAmbush1
     ; Science = SCIENCE_RebelAmbush2
     ; Science = SCIENCE_AnthraxBomb
     ; Science = SCIENCE_RebelAmbush3
     ; Science = SCIENCE_CashBounty1
   ; End
 ; End
;End

Object ChinaVehicleTroopCrawler
 ReplaceModule ModuleTag_02
  Body = ActiveBody ModuleTag_02_Override
    MaxHealth       = 270.0
    InitialHealth   = 270.0
  End
 End
END

Locomotor BattleMasterLocomotor
  Speed               = 35   ; in dist/sec
  SpeedDamaged        = 25   ; in dist/sec
End

Locomotor TroopCrawlerLocomotor
  Speed               = 30   ; in dist/sec
  SpeedDamaged        = 25   ; in dist/sec
End


Locomotor SupplyTruckLocomotor
  Speed                           = 30                ; in dist/sec
  SpeedDamaged                    = 25         ; in dist/sec
End

; ************* Added for Cinematic *****************
Locomotor CINE_BattleMasterLocomotor
  Speed                           = 25         ; in dist/sec
  SpeedDamaged                    = 15         ; in dist/sec
End

; ************* Added for Cinematic *****************
Locomotor CINE_TroopCrawlerLocomotor
  Speed                           = 25         ; in dist/sec
  SpeedDamaged                    = 15         ; in dist/sec
End

; ************* Added for Cinematic *****************
Locomotor CINE_SupplyTruckLocomotor
  Speed                           = 25         ; in dist/sec
  SpeedDamaged                    = 15         ; in dist/sec
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End


;CommandSet SCIENCE_GLA_CommandSetRank1
 ; 1 = Command_PurchaseScienceTechnicalTraining
 ; 2 = Command_PurchaseScienceMarauderTank
 ; 3 = Command_PurchaseScienceEmergencyRepair1
;END

; Rank 3 assign buttons to position like so:
; 1 4 7 10
; 2 5 8 11
; 3 6 9 12
;CommandSet SCIENCE_GLA_CommandSetRank3
  ;1 = Command_PurchaseScienceScudLauncher
  ;4 = Command_PurchaseScienceCashBounty1
 ; 5 = Command_PurchaseScienceCashBounty2
 ; 6 = Command_PurchaseScienceCashBounty3
 ; 7 = Command_PurchaseScienceRebelAmbush1
 ; 8 = Command_PurchaseScienceRebelAmbush2
 ; 9 = Command_PurchaseScienceRebelAmbush3
; 10 = Command_PurchaseScienceHijacker
;END

;; -------------------------------------
;; GLA Sciences
;; -------------------------------------

Object Demo_GLAVehicleScudLauncher
 Locomotor = SET_NORMAL RocketBuggyLocomotor
End


;-------------

SpecialPower SuperweaponScudStorm
  Enum                = SPECIAL_SCUD_STORM
  ReloadTime          = 480000   ; in milliseconds. min is 2x door/open close time!
  InitiateSound       = ScudStormInitiated
  PublicTimer         = Yes
  ViewObjectDuration  = 40000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 200  ; align with ObjectCreationList.ini's DeliveryDecalRadius
End
;----------------------------------
SpecialPower SuperweaponScudStormXR
  Enum                = SPECIAL_SCUD_STORM
  ReloadTime          = 300000   ; in milliseconds. min is 2x door/open close time!
  InitiateSound       = ScudStormInitiated
  PublicTimer         = Yes
  ViewObjectDuration  = 40000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 200  ; align with ObjectCreationList.ini's DeliveryDecalRadius
  ShortcutPower       = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify     = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End
;-----------------------------
Object Demo_GLAScudStorm
MaxSimultaneousOfType = 1
RemoveModule ModuleTag_10
AddModule ModuleTag_10
Behavior    = OCLSpecialPower ModuleTag_10
    SpecialPowerTemplate = SuperweaponScudStormXR
	;SpecialPower  = SuperweaponScudStormXR
    OCL = SUPERWEAPON_ScudStorm
  End
End
End



;--------------------------------------------------------
Weather
  SnowEnabled = yes             ;enable/disable snow on the map.
  SnowTexture = EXRainDrop.tga  ;texture used for each snow particle.
  
  SnowBoxDimensions = 100       ;width/height of box around camera containing snow.
  SnowBoxDensity = 1            ;amount of snow particles per world-unit. Raise to increase particle count.
 
  SnowFrequencyScaleX = 1       ;speed of side-to-side wave movement.
  SnowFrequencyScaleY = 1       ;speed of side-to-side wave movement. 
 
  SnowAmplitude = .1            ;amount of side-to-side movement. 
  SnowVelocity = 25.0           ;speed at which snow falls
  SnowPointSize = .3            ;scale the size of snow particles.
 
  ;Some video cards can't do hardware accelerated particles. Set this
  ;setting to "no" in order see what emulation will look like. Use the
  ;SnowQuadSize setting to make it look similar to PointSprite version.;;;

  SnowPointSprites = yes   ;set to "no" for point-sprite emulation.
  SnowQuadSize = .1        ;scale the size of snow particles when using point-sprite emulation.
End