Object AmericaParticleCannonUplink
  ShroudRevealToAllRange = 0  ; Reveals shroud to all players at a specific amount which can be different. 
                               ; Using same value? Then use KINDOF_REVEAL_TO_ALL instead!
END

Object GLAScudStorm
  ShroudRevealToAllRange = 0  ; Reveals shroud to all players at a specific amount which can be different. 
                               ; Using same value? Then use KINDOF_REVEAL_TO_ALL instead!
END

DialogEvent Taunts_GLABoss001
Filename = mg1ofg09.wav
End

DialogEvent Taunts_GLABoss002
Filename = mg1ofg10.wav
End

DialogEvent Taunts_GLABoss003
Filename = mg1ofg03.wav
End

DialogEvent Taunts_GLABoss004
Filename = mg1ofg04.wav
End

DialogEvent Taunts_GLABoss005
Filename = mg1bo101.wav
End

DialogEvent Taunts_GLABoss006
Filename = mg1ofg11.wav
End

DialogEvent Taunts_GLABoss007
Filename = mg1of12.wav
End

DialogEvent Taunts_GLABoss008
Filename = mg1ofg02.wav
End

DialogEvent Taunts_GLABoss009
Filename = mg1ofg05.wav
End

DialogEvent Taunts_GLABoss010
Filename = mg5bu104.wav
End

DialogEvent Taunts_GLABoss011
Filename = mg5ofg05.wav
End

DialogEvent Taunts_GLABoss012
Filename = mg5ofg08.wav
End

DialogEvent Taunts_GLABoss013
Filename = mg5ofg09.wav
End

DialogEvent Taunts_GLABoss014
Filename = mg6rb101.wav
End

DialogEvent Taunts_GLABoss015
Filename = mg6rb102.wav
End

DialogEvent Taunts_GLABoss016
Filename = mg6rb103.wav
End

DialogEvent Taunts_GLABoss017
Filename = mg6rb107.wav
End

DialogEvent Taunts_GLABoss018
Filename = mg6rb106.wav
End

DialogEvent Taunts_GLABoss019
Filename = mg5qu202.wav
End

DialogEvent Taunts_GLABoss020
Filename = mg5qu301.wav
End

DialogEvent Taunts_GLABoss021
Filename = mg5qu302.wav
End

DialogEvent Taunts_GLABoss022
Filename = mg2sc104.wav
End

DialogEvent Taunts_GLABoss023
Filename = mg2sc202.wav
End

DialogEvent Taunts_GLABoss024
Filename = mg2ofg02.wav
End

DialogEvent Taunts_GLABoss025
Filename = mg1sc109.wav
End