

;AIData
  ;StructureSeconds = 10 ;  Ai tries to build a new structure every N seconds.
  ;TeamSeconds = 60 ;  Ai tries to build a new team every N seconds.
 ; Wealthy = 14000 ;   Number of resources for the AI to consider itself wealthy
  ;Poor = 2000 ;   Number of resources for the AI to consider itself poor
  ;StructuresWealthyRate = 1.0 ;  (2=twice as fast) Rate modifier for structure building when wealthy.
 ; StructuresPoorRate = 0.5 ;  (0.5=half as fast) Rate modifier for structures when poor.
  ;TeamsWealthyRate = 1.0 ;   (2=twice as fast) Rate modifier for teams building when wealthy.
 ; TeamsPoorRate = 0.5 ;  (0.5=half as fast) Rate modifier for teams when poor.
;  TeamResourcesToStart = 0.80 ; (1.0=100%) Amount of resources required to start building a team. 
 ; GuardInnerModifierAI = 1.0 ;The radius modifier to vision which a guarding (AI Controlled) unit will agressively attack
 ; GuardOuterModifierAI = 2.0 ;The radius modifier to vision which a guarding (AI Controlled) unit will chase after
;  GuardInnerModifierHuman = 0.67 ;The radius modifier to vision which a guarding (Human Controlled) unit will agressively attack
;  GuardOuterModifierHuman = 1.0  ;The radius modifier to vision which a guarding (Human Controlled) unit will chase after
 ; GuardChaseUnitsDuration = 10000 ;The number of msec for which a guarding unit will chase attackers before giving up
  ;AttackPriorityDistanceModifier = 100.0; The distance required to reduce attack priority by 1.
  ;MaxRecruitRadius = 1500.0; The maximum distance a unit will be from a unit that recruits it.


;  SideInfo China
    ;ResourceGatherersEasy     = 1
   ; ResourceGatherersNormal   = 2
    ;ResourceGatherersHard     = 3     
    ;BaseDefenseStructure1     = ChinaGattlingCannon  

    ;SkillSet1
     ; Science = SCIENCE_RedGuardTraining
     ; Science = SCIENCE_ClusterMines
     ; Science = SCIENCE_NukeLauncher
     ; Science = SCIENCE_ArtilleryBarrage1
      ;Science = SCIENCE_ArtilleryTraining
     ; Science = SCIENCE_ArtilleryBarrage2
    ;End
 ; End

  ;SideInfo America
   ; ResourceGatherersEasy     = 1
   ; ResourceGatherersNormal   = 1
   ; ResourceGatherersHard     = 1   
   ; BaseDefenseStructure1     = AmericaPatriotBattery  

   ; SkillSet1
    ;  Science = SCIENCE_Pathfinder
     ; Science = SCIENCE_StealthFighter
      ;Science = SCIENCE_PaladinTank
      ;Science = SCIENCE_Paradrop1
      ;Science = SCIENCE_Paradrop2
     ; Science = SCIENCE_DaisyCutter
   ; End
  ;End
;End




;-----------------------------------------------------------------------------------
Object CINE_TrainEngine
  ReplaceModule ModuleTag_03
    Behavior = RailroadBehavior ModuleTag_03_Override
      PathPrefixName    = Railroad

    ;=== PARAMETERS FOR ALL CARRIAGES ===    
    RunningGarrisonSpeedMax = 1
    KillSpeedMin            = 1
    Friction                = 0.995
    BigMetalBounceSound     = BuildingFallingMetal
    SmallMetalBounceSound   = VehicleImpactHeavy
    MeatyBounceSound        = InfantryCrush
    ClicketyClackSound      = TrainClicketyClack
    WhistleSound            = TrainWhistle

    ;=== PARAMETERS THAT ARE MEANINGFUL ONLY WHEN IsLocomotive = Yes
    IsLocomotive         = Yes
    SpeedMax             = .88
    Acceleration         = 1.03
    WaitAtStationTime    = 10000     ; ten seconds
    Braking              = 0.97
    ; RunningSound         = TrainRunningLoop
    CrashFXTemplateName  = SpecialEffectsTrainCrashObject

    CarriageTemplateName = TrainCar03
    CarriageTemplateName = TrainCar03
    CarriageTemplateName = TrainCoal    
    CarriageTemplateName = TrainCab

    ;CarriageTemplateName = TrainCar01
    ;CarriageTemplateName = TrainCar02
    ;CarriageTemplateName = TrainCar03
    ;CarriageTemplateName = TrainCoal    
    ;CarriageTemplateName = TrainTank
    ;CarriageTemplateName = CabooseFullOfTerrorists
    End
  End
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
  SkyboxTextureN = TSMrnCldy_N.tga
  SkyboxTextureE = TSMrnCldy_E.tga
  SkyboxTextureS = TSMrnCldy_S.tga
  SkyboxTextureW = TSMrnCldy_W.tga
  SkyboxTextureT = TSMrnCldy_T.tga
End

;--------------------------------------------------------------------
Locomotor CINE_SupplyTruckLocomotor
Speed                           = 30                ; in dist/sec
TurnRate                        = 90             ; in degrees/sec
Acceleration                    = 50         ; in dist/(sec^2)
MinTurnSpeed                    = 15          ; in dist/sec
AccelerationPitchLimit          = 4              ; Angle limit how far chassis will lift or roll from acceleration.
  BounceAmount                    = 0                        ;  simulates hitting random rocks.  0==smooth pavement, 200 = bumpy.
  PitchStiffness                  = 0.2                    ;  stiffness of the "springs" in the suspension forward & back.
  RollStiffness                   = 0.05                    ;  stiffness of the "springs" in the suspension side to side.
  PitchDamping                    = 0.5                ;  How fast it damps.  0=perfect spring, bounces forever.  1=glued to terrain.
  RollDamping                     = 0.5                ;  How fast it damps.  0=perfect spring, bounces forever.  1=glued to terrain.
  ForwardAccelerationPitchFactor  = 0.02    ; How much acceleration will cause the front to lift, or dip for stops.
  LateralAccelerationRollFactor   = 0.02     ;   How much cornering will cause the chassis to roll.

  HasSuspension                   = Yes           ; Calculate 4 wheel independent suspension info.
  MaximumWheelExtension           = .2  ; Maximum distance the wheels will drop on the model.
  MaximumWheelCompression         = .2 ; Maximum distance the wheel will move up into the chassis.
  FrontWheelTurnAngle             = 22      ; How many degrees the front wheels can turn.

End

;-----------------------------------------------------------
Object BaikonurRocketDetonation
  ReplaceModule ModuleTag_08
  Behavior = NeutronMissileSlowDeathBehavior ModuleTag_08_Override
    DestructionDelay    = 3501
    ScorchMarkSize      = 1
    FXList              = FX_BaikonurNuke
    
    Blast1Enabled       = Yes
    Blast1Delay         = 580     ;in milliseconds
    Blast1ScorchDelay   = 100     ;in milliseconds
    Blast1InnerRadius   = 60.0    ;objects inside this get the full damage
    Blast1OuterRadius   = 60.0    ;objects inside this get some of the full damage
    Blast1MaxDamage     = 0.0     ;damage within inner radius of blast
    Blast1MinDamage     = 0.0     ;always do at least this much damage to objects
    Blast1ToppleSpeed   = 0.5     ;higher #'s topple faster
    Blast1PushForce     = 10.0    ;higher #'s push more
    
    Blast2Enabled       = Yes
    Blast2Delay         = 660    ;in milliseconds
    Blast2ScorchDelay   = 180     ;in milliseconds
    Blast2InnerRadius   = 90.0    ;objects inside this get the full damage
    Blast2OuterRadius   = 90.0    ;objects inside this get some of the full damage
    Blast2MaxDamage     = 0.0     ;damage within inner radius of blast
    Blast2MinDamage     = 0.0     ;always do at least this much damage to objects
    Blast2ToppleSpeed   = 0.45    ;higher #'s topple faster
    Blast2PushForce     = 8.0     ;higher #'s push more
    
    Blast3Enabled       = Yes
    Blast3Delay         = 720    ;in milliseconds
    Blast3ScorchDelay   = 260     ;in milliseconds
    Blast3InnerRadius   = 120.0   ;objects inside this get the full damage
    Blast3OuterRadius   = 120.0   ;objects inside this get some of the full damage
    Blast3MaxDamage     = 0.0     ;damage within inner radius of blast
    Blast3MinDamage     = 0.0     ;always do at least this much damage to objects
    Blast3ToppleSpeed   = 0.42    ;higher #'s topple faster
    Blast3PushForce     = 6.0     ;higher #'s push more

    Blast4Enabled       = Yes
    Blast4Delay         = 850    ;in milliseconds
    Blast4ScorchDelay   = 340     ;in milliseconds
    Blast4InnerRadius   = 150.0   ;objects inside this get the full damage
    Blast4OuterRadius   = 150.0   ;objects inside this get some of the full damage
    Blast4MaxDamage     = 0.0     ;damage within inner radius of blast
    Blast4MinDamage     = 0.0     ;always do at least this much damage to objects
    Blast4ToppleSpeed   = 0.40    ;higher #'s topple faster
    Blast4PushForce     = 6.0     ;higher #'s push more

    Blast5Enabled       = Yes
    Blast5Delay         = 1000    ;in milliseconds
    Blast5ScorchDelay   = 420     ;in milliseconds
    Blast5InnerRadius   = 180.0   ;objects inside this get the full damage
    Blast5OuterRadius   = 180.0   ;objects inside this get some of the full damage
    Blast5MaxDamage     = 0.0     ;damage within inner radius of blast
    Blast5MinDamage     = 0.0     ;always do at least this much damage to objects
    Blast5ToppleSpeed   = 0.38    ;higher #'s topple faster
    Blast5PushForce     = 6.0     ;higher #'s push more
    
    Blast6Enabled       = Yes
    Blast6Delay         = 1180    ;in milliseconds
    Blast6ScorchDelay   = 500     ;in milliseconds
    Blast6InnerRadius   = 60.0    ;objects inside this get the full damage
    Blast6OuterRadius   = 210.0   ;objects inside this get some of the full damage
    Blast6MaxDamage     = 0.0     ;damage within inner radius of blast
    Blast6MinDamage     = 0.0     ;always do at least this much damage to objects
    Blast6ToppleSpeed   = 0.35    ;higher #'s topple faster
    Blast6PushForce     = 4.0     ;higher #'s push more

    Blast7Enabled       = Yes
    Blast7Delay         = 999999  ;in milliseconds, don't do the damage wave
    Blast7ScorchDelay   = 620     ;in milliseconds
    Blast7OuterRadius   = 210.0   ;objects inside this get some of the full damage

    Blast8Enabled       = Yes
    Blast8Delay         = 999999  ;in milliseconds, don't do the damage wave    
    Blast8ScorchDelay   = 700     ;in milliseconds
    Blast8OuterRadius   = 210.0   ;objects inside this get some of the full damage

    Blast9Enabled       = Yes
    Blast9Delay         = 999999  ;in milliseconds, don't do the damage wave    
    Blast9ScorchDelay   = 800     ;in milliseconds
    Blast9OuterRadius   = 210.0   ;objects inside this get some of the full damage
    
    OCL            = MIDPOINT   OCL_PoisonFieldLarge

  End
  End
End

SpecialPower SuperweaponDaisyCutter
  Enum                = SPECIAL_DAISY_CUTTER
  ReloadTime          = 600000   ; in milliseconds
  RequiredScience     = SCIENCE_DaisyCutter
  PublicTimer         = Yes
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 30000  ; Lifetime of a Look done belonging to the firing player
  ViewObjectRange     = 250 ; And how far it can see
  RadiusCursorRadius  = 100
End
 
SpecialPower SuperweaponEMPPulse
  Enum                = SPECIAL_EMP_PULSE
  ReloadTime          = 660000   ; in milliseconds
  RequiredScience     = SCIENCE_EMPPulse
  PublicTimer         = Yes
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 30000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 200
End

SpecialPower SuperweaponNeutronMissile
  Enum                    = SPECIAL_NEUTRON_MISSILE
  ReloadTime              = 660000   ; in milliseconds. min is 2x door/open close time!
  InitiateSound           = AirRaidSiren  ; plays at source
  InitiateAtLocationSound = AirRaidSiren  ; plays at target
  PublicTimer             = Yes
  ViewObjectDuration      = 40000
  ViewObjectRange         = 250
  RadiusCursorRadius      = 210
End

SpecialPower SuperweaponParticleUplinkCannon
  Enum              = SPECIAL_PARTICLE_UPLINK_CANNON
  ReloadTime        = 540000 ; in milliseconds
  PublicTimer       = Yes
  ViewObjectDuration  = 30000
  ViewObjectRange     = 250
End


;--------------------------------------------------------------------
Object CINE_MogadishuHighrise03
  ReplaceModule ModuleTag_02
    Body = StructureBody ModuleTag_02_Override
      MaxHealth       = 10000.0
      InitialHealth   = 10000.0
    End
  End
End 

;CommandSet SCIENCE_GLA_CommandSetRank1
  ;1 = Command_PurchaseScienceTechnicalTraining
  ;2 = Command_PurchaseScienceMarauderTank
 ; 3 = Command_PurchaseScienceEmergencyRepair1
;END

; Rank 3 assign buttons to position like so:
; 1 4 7 10
; 2 5 8 11
; 3 6 9 12
;CommandSet SCIENCE_GLA_CommandSetRank3
  ;1 = Command_PurchaseScienceScudLauncher
 ; 4 = Command_PurchaseScienceCashBounty1
  ;5 = Command_PurchaseScienceCashBounty2
  ;6 = Command_PurchaseScienceCashBounty3
 ; 7 = Command_PurchaseScienceRebelAmbush1
  ;8 = Command_PurchaseScienceRebelAmbush2
  ;9 = Command_PurchaseScienceRebelAmbush3
 ;10 = Command_PurchaseScienceHijacker
;END

;; -------------------------------------
;; GLA Sciences
;; -------------------------------------
Object GLACommandCenter
Scale = 0.75
  ;GeometryMajorRadius = 40
  ;GeometryMinorRadius = 40
;GeometryHeight      = 14.0
;FactoryExitWidth    = 5 
 ;GeometryIsSmall     = Yes
End

Object Demo_GLACommandCenter
Scale = 0.75
End

Object Slth_GLACommandCenter
Scale = 0.75
End

Object Chem_GLACommandCenter
Scale = 0.75
End

Object Chem_GLAScudStorm
MaxSimultaneousOfType = 2
End

Object GLAScudStorm
MaxSimultaneousOfType = 2
End

Object Slth_GLAScudStorm
MaxSimultaneousOfType = 2
End

Object Demo_GLAScudStorm
MaxSimultaneousOfType = 2
End

Object Chem_GLAPalace
RemoveModule ModuleTag_10
AddModule ModuleTag_10
 Behavior = GarrisonContain ModuleTag_10
    ContainMax                    = 10
    EnterSound                    = GarrisonEnter
    ExitSound                     = GarrisonExit
    ImmuneToClearBuildingAttacks  = Yes
  End
End
End

Object Slth_GLAVehicleQuadCannon
AddModule ModuleTag_69
Behavior = StealthUpdate ModuleTag_69
    StealthDelay                          = 2000 ; msec
    StealthForbiddenConditions            = ATTACKING
    InnateStealth                         = Yes
    OrderIdleEnemiesToAttackMeUponReveal  = Yes
  End
End
End

Object Demo_GLAVehicleScudLauncher
 Locomotor = SET_NORMAL RocketBuggyLocomotor
End


