AIData
  AICrushesInfantry = No
End

Object AmericaStrategyCenter
  RemoveModule SpyTag_1
End

CommandSet SpecialPowerShortcutUSA
  1 = Command_A10ThunderboltMissileStrikeFromShortcut
  2 = Command_SelectAircraftCarriersFromShortcut
  3 = Command_SelectBattleshipsFromShortcut
  ; 4 = Command_SpyDroneFromShortcut
  4 = Command_ParadropFromShortcut
  ; 5 = Command_EmergencyRepairFromShortcut
  5 = Command_DaisyCutterFromShortcut
  6 = Command_FireParticleUplinkCannonFromShortcut
  7 = Command_NeutronMissileFromShortcut
  8 = Command_SpySatelliteScanFromShortcut
  9 = Command_SpectreGunshipFromShortcut
  10 = Command_LeafletDropFromShortcut
END

PlayerTemplate FactionAmerica
  ProductionCostChange = AmericaCommandCenter -50% ;Reduce Cost
  ProductionTimeChange = AmericaCommandCenter -80% ; Reduce Buildtime
End

PlayerTemplate FactionAmerica
  ProductionCostChange = AmericaTankAvenger -50% ;Reduce Cost
  ProductionTimeChange = AmericaTankAvenger -25% ; Reduce Buildtime
End

PlayerTemplate FactionChinaNukeGeneral
  ProductionTimeChange = Nuke_ChinaTankHunter -60% ; Reduce Buildtime
End

SpecialPower SpecialPowerBattleshipBombardment
  Enum               = SPECIAL_BATTLESHIP_BOMBARDMENT
  ReloadTime         = 180000 ; in milliseconds
  RadiusCursorRadius = 60
End

DialogEvent     MisUSA08General03      
   Filename =   mu8xou04.wav    
End

DialogEvent     MisUSA07Crusader117    
   Filename =   mu7cr117.wav    
End

CommandSet AmericaCommandCenterCommandSet
  1  = Command_ConstructAmericaDozer
  2  = Command_SpectreGunship
  4  = Command_LeafletDrop
  5  = Command_A10ThunderboltMissileStrike
  6  = Command_Paradrop
  7  = Command_SpyDrone
  8  = Command_EmergencyRepair
  9  = Command_DaisyCutter       ;NOTE THIS GETS UPGRADED BELOW
 10  = Command_SpySatelliteScan 
 13 = Command_SetRallyPoint
End

Object AmericaCommandCenter
 MaxSimultaneousOfType = 1
End

SpecialPower SuperweaponNeutronMissile
  Enum                    = NUKE_SPECIAL_NEUTRON_MISSILE
  ReloadTime              = 420000  ; in milliseconds. min is 2x door/open close time!
  InitiateSound           = AirRaidSiren  ; plays at source
  InitiateAtLocationSound = AirRaidSiren  ; plays at target
  PublicTimer             = Yes
  ViewObjectDuration      = 40000
  ViewObjectRange         = 250
  RadiusCursorRadius      = 210
  ShortcutPower           = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify         = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End

CommandSet ChinaVehicleHelixCommandSet
  1 = Command_TransportExit
  2 = Command_TransportExit
  3 = Command_TransportExit
  4 = Command_TransportExit
  5 = Command_TransportExit
  ;---------
  6 = Command_UpgradeChinaHelixBattleBunker
  8 = Command_UpgradeChinaHelixPropagandaTower
 10 = Command_UpgradeChinaHelixGattlingCannon
  ;---------
  ; 7 = Command_UpgradeChinaHelixNapalmBomb
  ; 9 = Command_ChinaHelixDropNapalmBomb
  ;---------
 11 = Command_AttackMove
 12 = Command_Evacuate 
 13 = Command_Guard
 14 = Command_Stop
End

SpecialPower SuperweaponEMPPulse
  Enum                = SPECIAL_EMP_PULSE
  ReloadTime          = 300000   ; in milliseconds
  RequiredScience     = SCIENCE_EMPPulse
  PublicTimer         = No
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 30000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 200
  ShortcutPower       = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify     = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End
