WaterTransparency
  TransparentWaterMinOpacity = 0.8   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 2.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
  StandingWaterTexture = TSWater03.tga
  ;StandingWaterColor = R:0 G:50 B:0
  ;StandingWaterColor = R:100 G:150 B:100
  StandingWaterColor = R:50 G:75 B:50
  ;AdditiveBlending = Yes
  RadarWaterColor = R:100 G:196 B:100
End

CommandSet SpecialPowerShortcutGLA
  1 = Command_AmbushFromShortcut
  2 = Command_EmergencyRepairFromShortcut
  3 = Command_AnthraxBombFromShortcut
  4 = Command_ScudStormFromShortcut
  5 = Command_RadarVanScanFromShortcut
  6 = Command_SneakAttackFromShortcut
  7 = Command_DaisyCutterFromShortcut
  8 = Command_GPSScramblerFromShortcut
END

DialogEvent Taunts_GLABoss001
Filename = mtrco106.wav
End

DialogEvent Taunts_GLABoss002
Filename = mtrofu01.wav
End

DialogEvent Taunts_GLABoss003
Filename = mg1sc109.wav
End

DialogEvent Taunts_GLABoss004
Filename = mg1sc205.wav
End

DialogEvent Taunts_GLABoss005
Filename = mg2ofg03.wav
End