; Remove stealth from mines
Object ChinaClusterMine
  RemoveModule ModuleTag_03
End


; Weapon MineDetonationFieldWeapon
;   PrimaryDamage = 200.0
;   PrimaryDamageRadius = 75.0
;   AttackRange = 50
;   DamageType = PARTICLE_BEAM
;   DeathType = LASERED
;   RadiusDamageAffects = ENEMIES NEUTRALS NOT_AIRBORNE
;   DelayBetweenShots = 500
; End


; Weapon MicrowaveTankEmitterWeapon
;   PrimaryDamage = 8.0
;   PrimaryDamageRadius = 100.0
;   DamageDealtAtSelfPosition = Yes
; ;  RadiusDamageAngle = 180  ; leaving field commented out in case anybody else wants to use it.  It's a good field.
;   AttackRange = 100.0
;   DamageType = MICROWAVE
;   DeathType = BURNED
;   WeaponSpeed = 600                     ;  dist/sec

;   FireFX = FX_MicrowaveTankEmitter ; This FxList is marked UseCallersRadius,
;   ; so the damage range can be tweaked and it will change the effect's radius too

;   RadiusDamageAffects = ENEMIES NOT_AIRBORNE
;   DelayBetweenShots = 250                ; time between shots, msec
; End


; Weapon DozerMineDisarmingWeapon
;   PrimaryDamage = 1.0             ; this isn't really used, but must be nonzero for targeting to work well
;   AttackRange = 5.0
;   DamageType = DISARM
;   DeathType = NORMAL
;   ProjectileObject = NONE
;   FireFX = WeaponFX_DozerMineDisarming
;   DelayBetweenShots = 0        ; time between shots, msec
;   ClipSize = 1                    ; how many shots in a Clip (0 == infinite)
;   ClipReloadTime = 1             ; how long to reload a Clip, msec
;   AntiGround = No
;   AntiProjectile = No
;   AntiSmallMissile = No
;   AntiMine = Yes
;   PreAttackDelay = 0           ; this is the natural duration of PRE scooping animation
;   PreAttackType = PER_ATTACK ; Do the delay every attack
;   ContinueAttackRange = 100        ; after disarming a mine, look for additional mines within this dist to disarm
; End


Weapon  MicrowaveTankBuildingDisabler
  PrimaryDamage         = 50.0
  PrimaryDamageRadius   = 0.0       ; 0 primary radius means "hits only intended victim"
  AttackRange           = 230.0  ; make it slightly outrange gatlings
  DamageType            = SUBDUAL_BUILDING
  DeathType             = NORMAL
  WeaponSpeed           = 999999.0          ; dist/sec (huge value == effectively instant)
  ;WeaponSpeed           = 10.0          ; dist/sec (huge value == effectively instant)
  LaserName             = MicrowaveDisableStream
  LaserBoneName         = WEAPON02
  RadiusDamageAffects   = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots     = 100               ; time between shots, msec
  ClipSize              = 0                    ; how many shots in a Clip (0 == infinite)
  ClipReloadTime        = 0              ; how long to reload a Clip, msec
  AntiAirborneVehicle   = No
  AntiAirborneInfantry  = No
  FireSound             = MicrowaveWeaponLoop
  FireSoundLoopTime = 120                ; loop the firing sound until there's this much delay between shots
End


; Weapon MicrowaveMineDisarmingWeapon
;   PrimaryDamage = 1.0             ; this isn't really used, but must be nonzero for targeting to work well
;   AttackRange = 120.0
;   PrimaryDamageRadius = 120.0
;   DamageDealtAtSelfPosition = Yes
;   DamageType = DISARM
;   DeathType = NORMAL
;   FireFX = FX_MicrowaveTankEmitter
;   AntiGround = No
;   AntiProjectile = No
;   AntiSmallMissile = No
;   AntiMine = Yes
;   RadiusDamageAffects = ENEMIES NOT_AIRBORNE
;   DelayBetweenShots = 10
;   WeaponSpeed = 600
; End


; Object AmericaTankMicrowave
;   AddModule
;     Behavior = FireWeaponUpdate ModuleTag_22B
;       Weapon = MicrowaveMineDisarmingWeapon
;     End
;   End
; End


Object AmericaWall
  AddModule
    Behavior = GrantUpgradeCreate ModuleTag_UPG1
      UpgradeToGrant        = Upgrade_AmericaTOWMissile
    End
    Behavior = GrantUpgradeCreate ModuleTag_UPG2
      UpgradeToGrant        = Upgrade_AmericaRangerFlashBangGrenade
    End
    Behavior = GrantUpgradeCreate ModuleTag_UPG3
      UpgradeToGrant        = Upgrade_AmericaCountermeasures
    End
    Behavior = GrantUpgradeCreate ModuleTag_UPG4
      UpgradeToGrant        = Upgrade_AmericaBunkerBusters
    End
    Behavior = GrantUpgradeCreate ModuleTag_UPG5
      UpgradeToGrant        = Upgrade_AmericaDroneArmor
    End
  End
End


; Give cine outro helixes gattling cannons by default.
; Object Tank_ChinaVehicleHelix
;   AddModule
;     Behavior = GrantUpgradeCreate ModuleTage_UPG1
;       UpgradeToGrant        = Upgrade_ChinaHelixGattlingCannon
;     End
;   End
; End

Upgrade Upgrade_ChinaHelixGattlingCannon
  DisplayName        = UPGRADE:HelixGattlingCannon
  Type               = OBJECT
  BuildTime          = 1.0
  BuildCost          = 100
  ButtonImage        = SNHelixUp01
  ResearchSound      = HelixVoiceUpgradeGattlingCannon
  UnitSpecificSound  = OverlordExpansion
End


Object AmericaInfantryColonelBurton
  AddModule
    Behavior = GrantUpgradeCreate ModuleTag_03
      UpgradeToGrant     = Upgrade_GLARadar
    End
    Behavior        = RadarUpgrade ModuleTag_05
      TriggeredBy   = Upgrade_GLARadar
      DisableProof  = Yes ; Won't be disabled by power low
    End
  End
End
