Object Demo_GLABlackMarket
MaxSimultaneousOfType = 4
End


;Object Demo_GLAInfantryTerrorist
;AddModule ModuleTag_33
;Behavior = StealthUpdate ModuleTag_33
   ; StealthDelay                          = 2000 ; msec
   ; StealthForbiddenConditions            = ATTACKING
   ; InnateStealth                         = Yes
    ;OrderIdleEnemiesToAttackMeUponReveal  = Yes
;End
;End
;End

;-----------------
;AI Stuff
;-----------------

AIData
  AICrushesInfantry                   = Yes   ; If yes, ai will attempt to crush infantry with vehicles.
End

;-----------------------
;Build Limits
;-----------------------


WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End

;; -------------------------------------
;; GLA Sciences
;; -------------------------------------