
ParticleSystem ChristmasMainStar
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 10.00 10.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:185 G:125 B:35 0
  Color2          = R:0 G:0 B:0 3
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:0.00 Y:0.00 Z:63.00
  VolLineEnd      = X:0.00 Y:0.00 Z:63.00
End

ParticleSystem ChristmasRedStar1
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:255 G:75 B:45 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:3.50 Y:0.00 Z:53.00
  VolLineEnd      = X:3.50 Y:0.00 Z:53.00
End

ParticleSystem ChristmasRedStar2
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:255 G:75 B:45 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:-4.00 Y:6.00 Z:33.00
  VolLineEnd      = X:-4.00 Y:6.00 Z:33.00
End

ParticleSystem ChristmasRedStar3
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:255 G:75 B:45 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:-2.00 Y:-11.00 Z:16.25
  VolLineEnd      = X:-2.00 Y:-11.00 Z:16.25
End

ParticleSystem ChristmasBlueStar1
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:45 G:75 B:255 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:3.85 Y:5.25 Z:42.00
  VolLineEnd      = X:3.85 Y:5.25 Z:42.00
End

ParticleSystem ChristmasBlueStar2
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:45 G:75 B:255 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:-7.65 Y:-5.25 Z:34.50
  VolLineEnd      = X:-7.65 Y:-5.25 Z:34.50
End

ParticleSystem ChristmasBlueStar3
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:45 G:75 B:255 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:12.00 Y:4.00 Z:19.65
  VolLineEnd      = X:12.00 Y:4.00 Z:19.65
End

ParticleSystem ChristmasGreenStar1
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:45 G:255 B:75 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:-3.65 Y:-6.45 Z:43.85
  VolLineEnd      = X:-3.65 Y:-6.45 Z:43.85
End

ParticleSystem ChristmasGreenStar2
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:45 G:255 B:75 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:7.25 Y:-6.65 Z:29.15
  VolLineEnd      = X:7.25 Y:-6.65 Z:29.15
End

ParticleSystem ChristmasGreenStar3
  Priority        = ALWAYS_RENDER
  Shader          = ADDITIVE
  Type            = PARTICLE
  ParticleName    = EXCounterMeasureFlare3.tga
  AngleZ          = 0.00 0.00
  AngularRateZ    = 0.00 0.00
  AngularDamping  = 0.00 0.00
  VelocityDamping = 0.00 0.00
  Gravity         = 0.00
  Lifetime        = 40.00 50.00
  SystemLifetime  = 0
  Size            = 2.00 3.00
  StartSizeRate   = 0.00 0.00
  SizeRate        = 3.00 3.00
  SizeRateDamping = 0.99 0.99
  Alpha1          = 1.00 1.00 0
  Alpha2          = 0.00 0.00 150
  Alpha3          = 0.00 0.00 0
  Color1          = R:45 G:255 B:75 0
  Color2          = R:0 G:0 B:0 2
  Color3          = R:0 G:0 B:0 0
  ColorScale      = 0.00 0.00
  BurstDelay      = 0.00 1.00
  BurstCount      = 5.00 8.00
  InitialDelay    = 0.00 0.00
  DriftVelocity   = X:0.00 Y:0.00 Z:0.00
  VelocityType    = ORTHO
  VelOrthoX       = 0.00 0.00
  VelOrthoY       = 0.00 0.00
  VelOrthoZ       = 0.00 0.00
  VolumeType      = LINE
  VolLineStart    = X:-7.00 Y:8.00 Z:16.25
  VolLineEnd      = X:-7.00 Y:8.00 Z:16.25
End

Object TreeChristmas
 AddModule
  Draw = W3DModelDraw ModuleTagNewModel_01
    ParticlesAttachedToAnimatedBones = Yes
    OkToChangeModelColor = Yes
    ExtraPublicBone = NETROPE05
    ConditionState  = NONE
      Model         = AVChinook_A1MSH
      ParticleSysBone = NETROPE05 ChristmasMainStar
      ParticleSysBone = NETROPE05 ChristmasRedStar1
      ParticleSysBone = NETROPE05 ChristmasRedStar2
      ParticleSysBone = NETROPE05 ChristmasRedStar3
      ParticleSysBone = NETROPE05 ChristmasBlueStar1
      ParticleSysBone = NETROPE05 ChristmasBlueStar2
      ParticleSysBone = NETROPE05 ChristmasBlueStar3
      ParticleSysBone = NETROPE05 ChristmasGreenStar1
      ParticleSysBone = NETROPE05 ChristmasGreenStar2
      ParticleSysBone = NETROPE05 ChristmasGreenStar3
    End
  End

  Draw = W3DModelDraw ModuleTagNewModel_02
    ParticlesAttachedToAnimatedBones = Yes
    AttachToBoneInAnotherModule = NETROPE05
    OkToChangeModelColor = Yes
    ConditionState = NONE
      Model        = PTPine01
    End
  End

  ArmorSet
    Conditions    = None
    Armor         = InvulnerableArmor
  End
  Body = HighlanderBody ModuleTagNew_01
    MaxHealth     = 50.0
    InitialHealth = 50.0
  End
  ClientUpdate = SwayClientUpdate ModuleTagNew_02
    ;None
  End
 End

  Scale               = 1.15
  DisplayName         = OBJECT:DogwoodTree OPTIMIZED_TREE
  KindOf              = SHRUBBERY IMMOBILE IGNORED_IN_GUI

  Geometry            = CYLINDER
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 4.0
  GeometryHeight      = 15
  Shadow              = SHADOW_DECAL
  InstanceScaleFuzziness = 0.1
End

Object CINE_AmericaInfantryRanger

RemoveModule ModuleTag_01

 AddModule
  Draw = W3DModelDraw ModuleTagNewModel_01

    OkToChangeModelColor = Yes
    ; --- Idle
    DefaultConditionState
      Model             = AIRngr_SKN
      Animation         = AIRngr_SKL.AIRngr_CHA
      AnimationMode     = LOOP
      WeaponFireFXBone  = PRIMARY Muzzle
      WeaponMuzzleFlash = PRIMARY MuzzleFX
      WeaponFireFXBone  = SECONDARY Muzzle
      WeaponLaunchBone  = SECONDARY Muzzle
    End

    ConditionState      = REALLYDAMAGED
      Animation         = AIRngr_SKL.AIRngr_CHB
      AnimationMode     = LOOP
   End
  End
 End
End

Object CINE_ChinaInfantryRedguard

RemoveModule ModuleTag_01

 AddModule
  Draw = W3DModelDraw ModuleTagNewModel_01

    OkToChangeModelColor = Yes
    ; --- Idle
    DefaultConditionState
      Model             = NICNSC_SKN
      Animation         = NICNSC_SKL.NICNSC_CHA
      AnimationMode     = LOOP
      WeaponFireFXBone  = PRIMARY Muzzle
      WeaponMuzzleFlash = PRIMARY MuzzleFX
      WeaponFireFXBone  = SECONDARY Muzzle
      WeaponLaunchBone  = SECONDARY Muzzle
    End

    ConditionState      = REALLYDAMAGED
      Animation         = NICNSC_SKL.NICNSC_CHA
      AnimationMode     = LOOP
   End
  End
 End
End

Object CINE_GLAInfantryRebel

RemoveModule ModuleTag_01

 AddModule
  Draw = W3DModelDraw ModuleTagNewModel_01

    OkToChangeModelColor = Yes
    ; --- Idle
    DefaultConditionState
      Model             = UIRGrd_SKN
      Animation         = UIRGrd_SKL.UIRGrd_CHA
      AnimationMode     = LOOP
      WeaponFireFXBone  = PRIMARY Muzzle
      WeaponMuzzleFlash = PRIMARY MuzzleFX
      WeaponFireFXBone  = SECONDARY Muzzle
      WeaponLaunchBone  = SECONDARY Muzzle
    End

    ConditionState      = REALLYDAMAGED
      Animation         = UIRGrd_SKL.UIRGrd_IDB
      AnimationMode     = LOOP
   End
  End
 End
End

FXList FX_FirePitExplode
  ParticleSystem 
    Name = MolotovFlames
  End
  ParticleSystem 
    Name = MolotovGlassShatter
  End
  TerrainScorch
    Type = RANDOM 
    Radius = 18
  End
  LightPulse 
    Color = R:255 G:128 B:51 
    Radius = 30 
    IncreaseTime = 0 
    DecreaseTime = 2333
  End
End

Object FirePit

RemoveModule ModuleTag_01
RemoveModule ModuleTag_02

 AddModule
  Draw = W3DModelDraw SpecificTag_01
    DefaultConditionState
      Model           = PMFirepit
      ParticleSysBone = None SmolderingFire
      ParticleSysBone = None SmolderingSmoke
    End
    ConditionState    = DAMAGED
      Model           = PMFirepit_D
      ParticleSysBone = None SmolderingFire
      ParticleSysBone = None SmolderingSmoke
    End
    AliasConditionState = REALLYDAMAGED
    AliasConditionState = RUBBLE
  End

  Body = ActiveBody SpecificTag_02
    MaxHealth     = 25.0
    InitialHealth = 25.0
  End

  Behavior = FXListDie SpecificTag_03
    DeathTypes = ALL
    DeathFX    = FX_FirePitExplode
  End
 End
End

Object CINE_GLAVehicleTechnicalChassisOne
RemoveModule ModuleTag_02
End

Object CINE_AmericaVehicleHumvee

RemoveModule ModuleTag_01

 AddModule
  Draw = W3DTruckDraw ModuleTagNewModel_01
    OkToChangeModelColor = Yes

    ConditionState = NONE
      Model  = AVHUMMER
      Turret = Turret
      HideSubObject = Turret MuzzleFX01 TurretUp01 Housecolor03
    End

    ConditionState = REALLYDAMAGED
      Model  = AVHUMMER_d
      Turret = Turret
      HideSubObject = Turret MuzzleFX01 TurretUp01 Housecolor03
    End

    ConditionState = WEAPONSET_PLAYER_UPGRADE
      Model  = AVHUMMER
      Turret = TurretUp01
      HideSubObject = Turret MuzzleFX01 TurretUp01 Housecolor03
    End

    ConditionState = REALLYDAMAGED WEAPONSET_PLAYER_UPGRADE
      Model  = AVHUMMER_d
      Turret = TurretUp01
      HideSubObject = Turret MuzzleFX01 TurretUp01 Housecolor03
    End
    TrackMarks         = EXTireTrack.tga
    Dust               = RocketBuggyDust
    DirtSpray          = RocketBuggyDirtSpray
    PowerslideSpray    = RocketBuggyDirtPowerSlide
    LeftFrontTireBone  = Tire01
    RightFrontTireBone = Tire02
    LeftRearTireBone   = Tire03
    RightRearTireBone  = Tire04
    TireRotationMultiplier = 0.2
    PowerslideRotationAddition = 1.25
  End
 End
End

Object CINE_ChinaVehicleTroopCrawlerEmpty

RemoveModule ModuleTag_01

 AddModule
  Draw = W3DTruckDraw ModuleTagNewModel_01
    OkToChangeModelColor = Yes
    ConditionState = NONE
      Model        = NVTClrI
    End
    ConditionState = REALLYDAMAGED RUBBLE
      Model        = NVTClrI_D
    End
    TrackMarks = EXTireTrack.tga
    Dust       = RocketBuggyDust
    DirtSpray  = RocketBuggyDirtSpray
    LeftFrontTireBone     = Wheel01
    RightFrontTireBone    = Wheel08
    LeftRearTireBone      = Wheel03
    RightRearTireBone     = Wheel05
    MidLeftFrontTireBone  = Wheel02
    MidRightFrontTireBone = Wheel07
    MidLeftRearTireBone   = Wheel04
    MidRightRearTireBone  = Wheel06
    TireRotationMultiplier      = 0.2
    PowerslideRotationAddition  = 0
  End
 End
End
