AIData
  AICrushesInfantry                   = No ; If yes, ai will attempt to crush infantry with vehicles.
End


Weather
  SnowEnabled = yes             ;enable/disable snow on the map.
  SnowTexture = EXRainDrop.tga  ;texture used for each snow particle.
  
  SnowBoxDimensions = 100       ;width/height of box around camera containing snow.
  SnowBoxDensity = 1            ;amount of snow particles per world-unit. Raise to increase particle count.
 
  SnowFrequencyScaleX = 1      ;speed of side-to-side wave movement.
  SnowFrequencyScaleY = 1      ;speed of side-to-side wave movement. 
 
  SnowAmplitude = .1            ;amount of side-to-side movement. 
  SnowVelocity = 25.0           ;speed at which snow falls
  SnowPointSize = .3            ;scale the size of snow particles.
 
  ;Some video cards can't do hardware accelerated particles. Set this
  ;setting to "no" in order see what emulation will look like. Use the
  ;SnowQuadSize setting to make it look similar to PointSprite version.;;;

  SnowPointSprites = yes ;set to "no" for point-sprite emulation.
  SnowQuadSize = .1 ;scale the size of snow particles when using point-sprite emulation.
End


Rank 1
  RankName                      = INI:RankLevel1
  SkillPointsNeeded             = 0
  SciencesGranted               = SCIENCE_Rank1
  SciencePurchasePointsGranted  = 1
End

Rank 2
  RankName                      = INI:RankLevel2
  SkillPointsNeeded             = 800 
  SciencesGranted               = SCIENCE_Rank2
  SciencePurchasePointsGranted  = 1
End

Rank 3
  RankName                      = INI:RankLevel3
  SkillPointsNeeded             = 1500
  SciencesGranted               = SCIENCE_Rank3
  SciencePurchasePointsGranted  = 1
End

Rank 4
  RankName                      = INI:RankLevel4
  SkillPointsNeeded             = 2500
  SciencesGranted               = SCIENCE_Rank4
  SciencePurchasePointsGranted  = 1
End

Rank 5
  RankName                      = INI:RankLevel5
  SkillPointsNeeded             = 5000
  SciencesGranted               = SCIENCE_Rank5
  SciencePurchasePointsGranted  = 1
End

PlayerTemplate FactionChina
  PurchaseScienceCommandSetRank1 = SCIENCE_CHINA_CommandSetRank1_Change
  PurchaseScienceCommandSetRank3 = SCIENCE_CHINA_CommandSetRank3_Change
  PurchaseScienceCommandSetRank8 = SCIENCE_CHINA_CommandSetRank8_Change
  SpecialPowerShortcutCommandSet = SpecialPowerShortcutChina_Change
End

;------------------------------------------------------------------------------
Object StanHanger02
  CommandSet       = StopOnlyGenericCommandSet
  RemoveModule ModuleTag_03
end

CommandSet SCIENCE_CHINA_CommandSetRank1_Change
  1 = Command_PurchaseScienceFrenzy2
END

CommandSet SCIENCE_CHINA_CommandSetRank3_Change
  1 = Command_PurchaseScienceFrenzy3
  4 = Infa_Command_PurchaseScienceInfantryParadrop1
  7 = Command_PurchaseScienceClusterMines
END

CommandSet SCIENCE_CHINA_CommandSetRank8_Change
  1 = Command_PurchaseScienceCarpetBomb
  2 = Infa_Command_PurchaseScienceInfantryParadrop2
END

CommandSet SpecialPowerShortcutChina_Change
  1 = Command_ClusterMinesFromShortcut
  3 = Infa_Command_ParadropFromShortcut
  4 = Command_LeafletDropFromShortcut
  7 = Command_ChinaCarpetBombFromShortcut
  8 = Command_FrenzyFromShortcut
END

Science SCIENCE_Frenzy2
  PrerequisiteSciences = SCIENCE_Rank1
  SciencePurchasePointCost = 1
  IsGrantable = Yes
  DisplayName = SCIENCE:ChinaFrenzy2
  Description = CONTROLBAR:ToolTipChinaScienceFrenzy
End

Science SCIENCE_Frenzy3
  PrerequisiteSciences = SCIENCE_Frenzy2 SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = Yes
  DisplayName = SCIENCE:ChinaFrenzy3
  Description = CONTROLBAR:ToolTipChinaScienceFrenzy
End

Science SCIENCE_LeafletDrop
  PrerequisiteSciences = SCIENCE_CHINA SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = Yes
  DisplayName = SCIENCE:USALeafletDrop
  Description = CONTROLBAR:ToolTipUSAScienceLeafletDrop
End

Science SCIENCE_ChinaCarpetBomb
  PrerequisiteSciences = SCIENCE_CHINA SCIENCE_Rank5
  SciencePurchasePointCost = 1
  IsGrantable = Yes
  DisplayName = SCIENCE:ChinaCarpetBomb
  Description = CONTROLBAR:ToolTipChinaScienceCarpetBomb
End

;-----------------------------------------------------------------------------
Science Infa_SCIENCE_InfantryParadrop1
  PrerequisiteSciences = SCIENCE_CHINA SCIENCE_Rank3
  SciencePurchasePointCost = 1
  IsGrantable = Yes
  DisplayName = SCIENCE:ChinaInfantryParadrop1
  Description = CONTROLBAR:Infa_ToolTipChinaScienceInfantryParadrop
End

Science Infa_SCIENCE_InfantryParadrop2
  PrerequisiteSciences = Infa_SCIENCE_InfantryParadrop1 SCIENCE_Rank5
  SciencePurchasePointCost = 1
  IsGrantable = Yes
  DisplayName = SCIENCE:ChinaInfantryParadrop2
  Description = CONTROLBAR:Infa_ToolTipChinaScienceInfantryParadrop
End

;-----------------------------------------------------------------------------
SpecialPower Infa_SuperweaponInfantryParadrop
  Enum                = INFA_SPECIAL_PARADROP_AMERICA
  ReloadTime          = 120000   ; in milliseconds
  RequiredScience     = Infa_SCIENCE_InfantryParadrop1
  PublicTimer         = No
  SharedSyncedTimer   = Yes
  RadiusCursorRadius  = 50
  ShortcutPower       = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify     = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End

;-----------------------------------------------------------------------------
SpecialPower SuperweaponLeafletDrop
  Enum                = SPECIAL_LEAFLET_DROP
  ReloadTime          = 120000   ; in milliseconds
  RequiredScience     = SCIENCE_LeafletDrop 
  PublicTimer         = No
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 30000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 110
  ShortcutPower       = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify     = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End

;-----------------------------------------------------------------------------
SpecialPower SuperweaponClusterMines
  Enum                = SPECIAL_CLUSTER_MINES
  ReloadTime          = 180000   ; in milliseconds
  RequiredScience     = SCIENCE_ClusterMines
  PublicTimer         = No
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 30000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 100
  ShortcutPower       = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify     = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End

;-----------------------------------------------------------------------------
SpecialPower SuperweaponFrenzy
  Enum                = SPECIAL_FRENZY
  ReloadTime          = 45000   ; in milliseconds. min is 2x door/open close time!
  RequiredScience     = SCIENCE_Frenzy2
;  InitiateSound       = FireArtilleryCannonSound
  PublicTimer         = No
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 30000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 200
  InitiateAtLocationSound = FrenzyActivate
  ShortcutPower       = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify     = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End

;-----------------------------------------------------------------------------
SpecialPower SuperweaponChinaCarpetBomb
  Enum                = SPECIAL_CHINA_CARPET_BOMB
  ReloadTime          = 180000   ; in milliseconds
  RequiredScience     = SCIENCE_ChinaCarpetBomb
  PublicTimer         = No
  SharedSyncedTimer   = Yes
  ViewObjectDuration  = 40000
  ViewObjectRange     = 250
  RadiusCursorRadius  = 180
  ShortcutPower       = Yes     ;Capable of being fired by the side-bar shortcut.
  AcademyClassify     = ACT_SUPERPOWER ;Considered a powerful special power that a player could fire. Not for simpler unit based powers.
End

; -----------------------------------------------------------------------------
ObjectCreationList Infa_SUPERWEAPON_Paradrop1
  DeliverPayload
    Transport = ChinaJetCargoPlane
    StartAtPreferredHeight = Yes
    StartAtMaxSpeed = Yes
    MaxAttempts = 4
    DropOffset = X:0 Y:0 Z:-10
    DropDelay = 150         ; time in between each item dropped (if more than one)
    ParachuteDirectly = Yes ; will tell all contained parachutes to go ahead and bunch
    PutInContainer = AmericaParachute
    Payload = ChinaInfantryRedguard 5
    Payload = AmericaVehicleMedic 1
    DeliveryDistance = 0  ;when outbound vehicle must be this close to target to continue delivery
    PreOpenDistance = 300 ;When inbound, vehicle can be this much farther than DeliveryDistance to begin delivery 
    DeliveryDecalRadius = 50
    DeliveryDecal
      Texture           = SCCParadrop_USA
      Style             = SHADOW_ALPHA_DECAL
      OpacityMin        = 25%
      OpacityMax        = 50%
      OpacityThrobTime  = 500
      Color             = R:227 G:229 B:22 A:255 
      OnlyVisibleToOwningPlayer = Yes
    End
    ;RequiresLivePlayer = Yes ; I want to require a live player, but I'll settle for dropping neutral rangers instead
  End
End

; -----------------------------------------------------------------------------
ObjectCreationList Infa_SUPERWEAPON_Paradrop2
  DeliverPayload
    Transport = ChinaJetCargoPlane
    StartAtPreferredHeight = Yes
    StartAtMaxSpeed = Yes
    MaxAttempts = 4
    DropOffset = X:0 Y:0 Z:-10
    DropDelay = 80        ; time in between each item dropped (if more than one)
    ParachuteDirectly = Yes ; will tell all contained parachutes to go ahead and bunch
    PutInContainer = AmericaParachute
    Payload = ChinaInfantryRedguard 10
    Payload = AmericaVehicleMedic 1
    DeliveryDistance = 0  ;when outbound vehicle must be this close to target to continue delivery
    PreOpenDistance = 300 ;When inbound, vehicle can be this much farther than DeliveryDistance to begin delivery 
    DeliveryDecalRadius = 50
    DeliveryDecal
      Texture           = SCCParadrop_USA
      Style             = SHADOW_ALPHA_DECAL
      OpacityMin        = 25%
      OpacityMax        = 50%
      OpacityThrobTime  = 500
      Color             = R:227 G:229 B:22 A:255 
      OnlyVisibleToOwningPlayer = Yes
    End
    ;RequiresLivePlayer = Yes ; I want to require a live player, but I'll settle for dropping neutral rangers instead
  End
End



;------------------------------------------------------------------------------
Object ChinaJetCargoPlane
  AddModule
    Behavior    = OCLSpecialPower ModuleTag_SPInfantryParadrop
      SpecialPowerTemplate = Infa_SuperweaponInfantryParadrop
      UpgradeOCL           = Infa_SCIENCE_InfantryParadrop2 Infa_SUPERWEAPON_Paradrop2
      OCL                  = Infa_SUPERWEAPON_Paradrop1
      CreateLocation       = USE_OWNER_OBJECT
      ScriptedSpecialPowerOnly = Yes
    End 
  End  
End

;------------------------------------------------------------------------------
Object ChinaCommandCenter
  AddModule
    Behavior = CashBountyPower ModuleTag_SPCashBounty
      SpecialPowerTemplate    = SpecialAbilityCashBounty1
      Bounty                  = 1%
    End
  End
  AddModule
    Behavior           = OCLSpecialPower ModuleTag_SPInfantryParadrop
      SpecialPowerTemplate = Infa_SuperweaponInfantryParadrop
      UpgradeOCL           = Infa_SCIENCE_InfantryParadrop2 Infa_SUPERWEAPON_Paradrop2
      OCL                  = Infa_SUPERWEAPON_Paradrop1
      CreateLocation       = CREATE_AT_EDGE_NEAR_SOURCE
      OCLAdjustPositionToPassable = Yes ;Like RA2, shift target to passable cell so we don't land in water and on cliffs.
    End 
  End 
  AddModule
    Behavior           = OCLSpecialPower ModuleTag_SPLeafletDrop
      SpecialPowerTemplate = SuperweaponLeafletDrop
      OCL                  = SUPERWEAPON_LeafletDrop
      CreateLocation       = CREATE_AT_EDGE_NEAR_SOURCE
    End
  End
  AddModule
    Behavior           = OCLSpecialPower ModuleTag_SPCarpetBomb
      SpecialPowerTemplate = SuperweaponChinaCarpetBomb
      OCL                  = SUPERWEAPON_ChinaCarpetBomb
      CreateLocation       = CREATE_AT_EDGE_NEAR_SOURCE
    End 
  End
End

;------------------------------------------------------------------------------
Object ChinaBarracks
  CommandSet       = ChinaBarracksCommandSet_Change
End

;------------------------------------------------------------------------------
; Also known as the Ambulance
Object AmericaVehicleMedic
  UpgradeCameo1 = NONE
  UpgradeCameo2 = NONE
  UpgradeCameo3 = NONE
  UpgradeCameo4 = NONE
  UpgradeCameo5 = NONE

  Prerequisites
    Object = ChinaBarracks
  End
  WeaponSet
    Conditions = None 
    Weapon = PRIMARY HumveeGun
  End
  Locomotor       = SET_NORMAL GattlingTankLocomotor
  RemoveModule ModuleTag_03
  RemoveModule ModuleTag_04
  RemoveModule ModuleTag_09
  RemoveModule ModuleTag_10
  RemoveModule ModuleTag_19
  RemoveModule ModuleTag_11
End

;------------------------------------------------------------------------------
Object MilitiaTank
  ; *** ART Parameters ***
  SelectPortrait         = SNBattlemaster_L
  ButtonImage            = SNBattlemaster

  Prerequisites
    Object = ChinaBarracks
  End
  WeaponSet
    Conditions           = None 
    Weapon               = PRIMARY Nuke_BattleMasterTankGun
  End
  ArmorSet
    Conditions           = None
    Armor                = TruckArmor
    DamageFX             = TankDamageFX
  End
End

;------------------------------------------------------------------------------
CommandSet ChinaBarracksCommandSet_Change
  1 = Command_ConstructChinaInfantryRedguard
 13 = Command_SetRallyPoint
End

; -----------------------------------------------------------------------------
Object Slth_GLASneakAttackTunnelNetworkStart
  RemoveModule ModuleTag_11
  AddModule
    Behavior             = CreateObjectDie ModuleTag_Debris
      CreationList  = OCL_ABTunnelNetworkDebris
    End
  End
  AddModule
    Behavior             = FXListDie ModuleTag_DeathEffect
      DeathFX       = FX_StructureSmallDeath
    End
  End
  AddModule
    Behavior             = FXListDie ModuleTag_DeathEffect1
      DeathFX       = FX_BunkerBusterExplosion
    End
  End
End

; -----------------------------------------------------------------------------
Object GLASneakAttackTunnelNetwork
  AddModule
    Behavior = AutoHealBehavior ModuleTag_Heal
      HealingAmount = 5
      HealingDelay = 1000 ; msec
      StartsActive      = Yes
    End
  End
End

;------------------------------------------------------------------------------
Object AmphibiousTransport
  RemoveModule ModuleTag_03
  AddModule
    Body              = ActiveBody ModuleTag_03
      MaxHealth       = 500.0
      InitialHealth   = 500.0
    End
  End
End

;------------------------------------------------------------------------------
Object AmericaInfantryRanger
  VisionRange = 200
  WeaponSet
    Conditions = None 
    Weapon = PRIMARY RangerAdvancedCombatRifle
  End
  WeaponSet
    Conditions = PLAYER_UPGRADE 
    Weapon = PRIMARY RangerAdvancedCombatRifle
    Weapon = SECONDARY RangerFlashBangGrenadeWeapon
    AutoChooseSources = PRIMARY FROM_SCRIPT
    AutoChooseSources = SECONDARY FROM_SCRIPT
    WeaponLockSharedAcrossSets = Yes ; This set is so similar to the default set that it can hold the weapon lock
  End
End

;------------------------------------------------------------------------------
Object AmericaInfantryOfficer
  VisionRange = 200
End

;------------------------------------------------------------------------------
Object ChinaInfantryRedguard
  UpgradeCameo1 = NONE
  UpgradeCameo2 = NONE

  VisionRange = 200
  WeaponSet
    Conditions           = None 
    Weapon               = PRIMARY TechnicalMachineGunWeapon
  End
  ArmorSet
    Conditions      = None
    Armor           = ChemSuitHumanArmor
    DamageFX        = InfantryDamageFX
  End
  VisionRange = 150
  CommandSet    = GenericCommandSet

  RemoveModule ModuleTag_06

  GeometryMajorRadius = 4.0
  GeometryMinorRadius = 4.0
End

;------------------------------------------------------------------------------
Object ChinaInfantryOfficer
  VisionRange = 200
  WeaponSet
    Conditions           = None 
    Weapon               = PRIMARY TechnicalMachineGunWeapon
  End
  ArmorSet
    Conditions      = None
    Armor           = ChemSuitHumanArmor
    DamageFX        = InfantryDamageFX
  End
  VisionRange = 150
  CommandSet    = GenericCommandSet
  Locomotor = SET_NORMAL RedguardLocomotor

  GeometryMajorRadius = 4.0
  GeometryMinorRadius = 4.0
End

;------------------------------------------------------------------------------
Object GLAInfantryRebel
  VisionRange = 200
End

;------------------------------------------------------------------------------
Object Slth_GLAInfantryRebel
  VisionRange = 200
End

;------------------------------------------------------------------------------
Object Chem_GLAInfantryRebel
  VisionRange = 200
End

;------------------------------------------------------------------------------
Object TechOilDerrick
  KindOf = +IMMUNE_TO_CAPTURE

  RemoveModule ModuleTag_03
  AddModule
    Body                 = StructureBody ModuleTag_03
      MaxHealth          = 1500.0
      InitialHealth      = 1500.0
    End
  End

  AddModule
    Behavior = AutoHealBehavior ModuleTag_Heal
      HealingAmount = 5
      HealingDelay = 1000 ; msec
      StartsActive      = Yes
    End
  End

  RemoveModule ModuleTag_04
  AddModule
    Behavior              = AutoDepositUpdate ModuleTag_Deposit
      DepositTiming       = 30000  ; in milliseconds
      DepositAmount       = 200    ; cash amount to deposit every Deposit Timings
    End
  End
END

;------------------------------------------------------------------------------
Object Tent01
  KindOf            = STRUCTURE IMMOBILE
  RemoveModule ModuleTag_03
End

;------------------------------------------------------------------------------
Object Tent02
  KindOf            = STRUCTURE IMMOBILE
  RemoveModule ModuleTag_03
End

;------------------------------------------------------------------------------
Object Tent03
  KindOf            = STRUCTURE IMMOBILE
  RemoveModule ModuleTag_03
End

;------------------------------------------------------------------------------
Object Tent04
  KindOf            = STRUCTURE IMMOBILE
  RemoveModule ModuleTag_03
End

;------------------------------------------------------------------------------
Object GermanCastle
  KindOf            = STRUCTURE IMMOBILE
  RemoveModule ModuleTag_03
End

