;GLA02 Map.ini

AIData
  StructureSeconds = 10.0 ;  Ai tries to build a new structure every N seconds.
  TeamSeconds = 50.0 ;  Ai tries to build a new team every N seconds.
  Wealthy = 14000 ;   Number of resources for the AI to consider itself wealthy
  Poor = 2000 ;   Number of resources for the AI to consider itself poor
  StructuresWealthyRate = 2.0 ;  (2=twice as fast) Rate modifier for structure building when wealthy.
  StructuresPoorRate = 0.6 ;  (0.5=half as fast) Rate modifier for structures when poor.
  TeamsWealthyRate = 1.5 ;   (2=twice as fast) Rate modifier for teams building when wealthy.
  TeamsPoorRate = 1.0 ;  (0.5=half as fast) Rate modifier for teams when poor.
  TeamResourcesToStart = 0.80 ; (1.0=100%) Amount of resources required to start building a team. 
  GuardInnerModifierAI = 0.67 ;The radius modifier to vision which a guarding (AI Controlled) unit will agressively attack
  GuardOuterModifierAI = 1.0 ;The radius modifier to vision which a guarding (AI Controlled) unit will chase after
;  GuardInnerModifierHuman = 0.67;The radius modifier to vision which a guarding (Human Controlled) unit will agressively attack
;  GuardOuterModifierHuman = 1.0  ;The radius modifier to vision which a guarding (Human Controlled) unit will chase after
  GuardChaseUnitsDuration = 5000 ;The number of msec for which a guarding unit will chase attackers before giving up
  MaxRecruitRadius = 1500.0; The maximum distance a unit will be from a unit that recruits it.
  EnableRepulsors = No ; If yes, KINDOF_CAN_BE_REPULSED will run from enemies & repulsors.

  SideInfo America
    ResourceGatherersEasy     = 0
    ResourceGatherersNormal   = 1
    ResourceGatherersHard     = 2   
    BaseDefenseStructure1     = AmericaPatriotBattery  

    SkillSet1
      Science = SCIENCE_SpyDrone
      Science = SCIENCE_PaladinTank
      Science = SCIENCE_Paradrop1
    End
  End
End


Object MogadishuMaleCivilian01
  KindOf = +SELECTABLE -CAN_BE_REPULSED
END

Object MogadishuMaleCivilian02
  KindOf = +SELECTABLE -CAN_BE_REPULSED
END

Object MogadishuMaleCivilian03
  KindOf = +SELECTABLE -CAN_BE_REPULSED
END

Object MogadishuFemaleCivilian01
  KindOf = +SELECTABLE -CAN_BE_REPULSED
END

Object MogadishuFemaleCivilian02
  KindOf = +SELECTABLE -CAN_BE_REPULSED
END


Object CINEConvoyTruck
  RadarPriority = UNIT
END

Object ConvoyTruck04
  RadarPriority = UNIT

  AddModule
    Behavior                = CreateCrateDie ModuleTag_MapOverride01
      CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object ConvoyTruck01
  RadarPriority = UNIT

  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
      CrateData            = GLA02_Always100DollarCrate
    End
  End
END

Object Humvee1
  ReplaceModule ModuleTag_CratesChange
    Behavior                    = CreateCrateDie ModuleTag_CratesChange_Override
      CrateData            = GLA02_Always1000DollarCrate
    End
  End
END



Object AmericaTankCrusader
  ReplaceModule ModuleTag_CratesChange
    Behavior                    = CreateCrateDie ModuleTag_CratesChange_Override
      CrateData            = GLA02_Always1000DollarCrate
    End
  End
END

Object AmericaVehicleChinook
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AmericaJetRaptor
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AmericaJetB52
  AddModule
    Behavior                = CreateCrateDie ModuleTag_MapOverride01
      CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object AmericaVehicleHumvee
  ReplaceModule ModuleTag_CratesChange
    Behavior                    = CreateCrateDie ModuleTag_CratesChange_Override
      CrateData            = GLA02_Always1000DollarCrate
    End
  End
END

Object AmericaVehicleComanche
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AmericaJetCargoPlane
 KindOf = +SELECTABLE
  ReplaceModule ModuleTag_03
   Body = ActiveBody ModuleTag_03_Override
     MaxHealth       = 750.0
     InitialHealth   = 750.0
   End
  End

  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END

Object AmericaVehicleDozer
  ReplaceModule ModuleTag_CratesChange
    Behavior                    = CreateCrateDie ModuleTag_CratesChange_Override
      CrateData            = GLA02_Always1000DollarCrate
    End
  End
END




Object AmericaCommandCenter
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object AmericaBarracks
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object AmericaWarFactory
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object AmericaPowerPlant
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object AmericaSupplyCenter
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object AmericaPatriotBattery
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END



Object QuonsetHut01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always200DollarCrate
    End
  End
END

Object Shack
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END

Object BarnCoop
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object BarnShed
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object FarmHouse
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object WatchTower03
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END

Object RiverHouse01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END

Object RiverHouse02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END

Object MogadishuGarage
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END


Object GasStation03
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object AsianApartmentUnit
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1500DollarCrate
    End
  End
END


Object MogadishuHouse01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END


Object StanRestaurant02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object StanSmallRetail02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuShop01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object StanSchool02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object StanSmallRetail03
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object StanConvenienceStore01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object StanConvenienceStore02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object StanApartment02
  AddModule

    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHouse05
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHouse09
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHouse10
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHouse06
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHouse02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHouse04
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object AsiaGovernmentBuilding
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHighrise03
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END


Object StanHotel01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object AsiaApartment02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object AsisApartment01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object MogadishuHighrise01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object StanRestaurant01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object AsianTrainStation02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always1000DollarCrate
    End
  End
END

Object IndustrialBuilding02
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always2500DollarCrate
    End
  End
END

Object JunkDealer
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END

Object MarketVender03
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END

Object MarketVender01
  AddModule
    Behavior               = CreateCrateDie ModuleTag_MapOverride01
     CrateData             = GLA02_Always100DollarCrate
    End
  End
END




Object 100DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 100
      BuildingPickup = No
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      ForbidOwnerPlayer      = Yes
    End
  End
END

Object 200DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 200
      BuildingPickup = No
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      ForbidOwnerPlayer      = Yes
    End
  End
END

Object 1000DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 1000
      BuildingPickup = No
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      ForbidOwnerPlayer      = Yes
    End
  End
END

Object 1500DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 1500
      BuildingPickup = No
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      ForbidOwnerPlayer      = Yes
    End
  End
END

Object 2500DollarCrate
  ReplaceModule ModuleTag_ForbiddenChanges
    Behavior = MoneyCrateCollide ModuleTag_ForbiddenChanges_Override
      ForbiddenKindOf = PROJECTILE
      MoneyProvided = 2500
      BuildingPickup = No
      ExecuteAnimation       = MoneyPickUp
      ExecuteAnimationTime   = 4.0    ; In seconds
      ExecuteAnimationZRise  = 15.0   ; Z world units per second to rise
      ExecuteAnimationFades  = Yes    ; Animation does/doesn't fade out
      ForbidOwnerPlayer      = Yes
    End
  End
END


Locomotor B52Locomotor
  Speed = 65  ;100          ; in dist/sec
  SpeedDamaged = 40         ; in dist/sec
  TurnRate = 30             ; in degrees/sec
  TurnRateDamaged = 25      ; in degrees/sec
End




Locomotor SupplyTruckLocomotor
  Speed = 45
  SpeedDamaged = 45
End


ObjectCreationList SUPERWEAPON_CrateDrop
  DeliverPayload
    Transport = AmericaJetCargoPlane
    StartAtPreferredHeight = Yes
    StartAtMaxSpeed = Yes
    MaxAttempts = 4
    DropOffset = X:0 Y:0 Z:-5
    DropDelay = 300  ;500       ; time in between each item dropped (if more than one)
    PutInContainer = AmericaParachute
    Payload = 200DollarCrate 10
    DeliveryDistance = 250
    DeliveryDecalRadius = 0
    DeliveryDecal
      Texture           = EXTargeterAlpha
      Style             = SHADOW_ALPHA_DECAL
      OpacityMin        = 50%
      OpacityMax        = 100%
      OpacityThrobTime  = 500
      Color             = R:255 G:0 B:255 A:255 
      OnlyVisibleToOwningPlayer = Yes
    End
  End
End


Object Hedge1
  KindOf = +CAN_SEE_THROUGH_STRUCTURE
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End


;; -------------------------------------
;; GLA Sciences
;; -------------------------------------


;************************* Cinematic ***********************************************
Object CINE_GLAInfantryRebel
  WeaponSet
    Conditions = None 
    Weapon = PRIMARY CINE_GLARebelMachineGun
  End
  
  VisionRange         = 350
End  