
Upgrade Upgrade_Nationalism
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Upgrade_ChinaChainGuns
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Upgrade_ChinaSubliminalMessaging
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Upgrade_ChinaUraniumShells
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Upgrade_ChinaNuclearTanks
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Tank_Upgrade_ChinaTankAutoLoader
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Upgrade_ChinaOverlordGattlingCannon
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Upgrade_ChinaOverlordPropagandaTower
  BuildTime          = 0
  BuildCost          = 0
End

Upgrade Upgrade_ChinaOverlordBattleBunker
  BuildTime          = 0
  BuildCost          = 0
End

Locomotor TroopCrawlerLocomotor
  Speed               = 20   ; in dist/sec
  SpeedDamaged        = 18   ; in dist/sec
  TurnRate            = 90   ; in degrees/sec
  TurnRateDamaged     = 60   ; in degrees/sec
  Acceleration        = 30   ; in dist/(sec^2)
  AccelerationDamaged = 8    ; in dist/(sec^2)
  Braking             = 50  ; in dist/(sec^2)
End

Weather
 SnowEnabled = yes             ; enable/disable snow on the map.
 SnowTexture = ExSnowFlake.tga ; texture used for each snow particle.
 SnowBoxDimensions = 100       ; width/height of box around camera containing snow.
 SnowBoxDensity = 1            ; amount of snow particles per world-unit. Raise to increase particle count.
 SnowFrequencyScaleX = 0.0533  ; speed of side-to-side wave movement.
 SnowFrequencyScaleY = 0.0275  ; speed of side-to-side wave movement. 
 SnowAmplitude = 4.0           ; amount of side-to-side movement. 
 SnowVelocity = 3.0            ; speed at which snow falls
 SnowPointSize = .16           ; scale the size of snow particles.
 SnowMaxPointSize = 10.0       ; maximum pixel size of point sprite particles (min-spec requires <= 64).
 SnowMinPointSize = 0.0        ; minimum pixel size of point sprite particles.

 ;Some video cards can't do hardware accelerated particles.  Set this
 ;setting to "no" in order see what emulation will look like.  Use the
 ;SnowQuadSize setting to make it look similar to PointSprite version.

 SnowPointSprites = yes   ;set to "no" for point-sprite emulation.
 SnowQuadSize = 0.5       ;scale the size of snow particles when using point-sprite emulation.
End

;------------------------------------------
;--------Set Environment Overrides---------
;------------------------------------------


WaterTransparency
  TransparentWaterMinOpacity = 0.8   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 2.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
  StandingWaterTexture = TSWater03.tga
  ;StandingWaterColor = R:116 G:216 B:252
  ;StandingWaterColor = R:116 G:216 B:252
  StandingWaterColor = R:116 G:216 B:252
  ;AdditiveBlending = Yes
  RadarWaterColor = R:116 G:216 B:252
End
