

;Gramantio Specifc map.ini
;
;I use this because I put the trees that were made by Gram. without even notice
;-Cresty

Object TreeDogwood02Yellow

 AddModule
  Draw = W3DTreeDraw SpecificTag_01
    ModelName        = PTDogwod02
    TextureName      = PTOakFall4.tga

    DoTopple         = Yes
    DoShadow         = Yes
    DoShadow         = Yes
    ToppleFX         = FX_ToppleTreeYellowSmall
    BounceFX         = FX_TreeBounce
    KillWhenFinishedToppling = Yes
    SinkDistance     = 10
    SinkTime         = 5000
  End

  ClientUpdate = SwayClientUpdate SpecificTag_02
    ;None
  End

  Behavior = DestroyDie SpecificTag_03
    ;None
  End
 End

  DisplayName         = OBJECT:DogwoodTree
  CrushableLevel      = 1
  KindOf              = SHRUBBERY IMMOBILE IGNORED_IN_GUI OPTIMIZED_TREE

  Geometry            = CYLINDER
  GeometryIsSmall     = Yes
  GeometryMajorRadius = 3.0
  GeometryHeight      = 8.0
  Shadow              = SHADOW_DECAL
  InstanceScaleFuzziness = 0.1

  RemoveModule ModuleTag_DefaultDestroyDie
  RemoveModule ModuleTag_DefaultInactiveBody
  RemoveModule ModuleTag_DefaultW3DDefaultDraw
End

